### ISSUE TITLE
Select default format using filetype

### ISSUE THREAD

**Issue by naught101** [vim-voom/vim-voom.github.com#15]
`:Voom` would be a more friendly command if it defaulted to the appropriate fold type for the filetype. The start fold level markers could still be used by default if the filetype is not recognised.

Very few users of most of the documentation formats (and probably most of the code formats) that Voom supports would be happy to leave in start folds in the code - it's really messy for any users of other systems, and it gets in the way when not using Voom. That means that _every time_ you want to use voom on markdown, you have to type `:Voom rest`, but the second part of that command is redundant, because no other Voom command will work properly anyway.

**Comment by vim-voom** [comment]
I will not do this. I like fold markers. I made some small changes in
v5.2 to reduce initial confusion. By default, :Voom is now exactly
identical to ":Voom fmr", that is it imports voom_mode_fmr.py. So the
default mode is truly "fmr" mode. Help file was slightly rearranged to
treat fold markers more like other markups.
