### ISSUE TITLE
Using voom with multiple buffers open

### ISSUE THREAD

**Issue by rightaway** [vim-voom/vim-voom.github.com#20]
I was using voom earlier with multiple tabs, and things worked great. If I switched a tab, the new tab would either have or not have the voom contents depending on whether it had already been opened.

Now I've switched to using buffers, and when I open voom in one buffer and switch buffers, of course the voom screen corresponds to the previous buffer and not the new one. Is there a way around this?

Otherwise everytime I switch a buffer I have to re-run the voom command. Maybe there's a way to do this automatically using some change to the vimrc? Or could this be a feature request?

**Comment by vim-voom** [comment]
This seems to mostly work:
https://github.com/vim-voom/VOoM_extras/blob/master/addons/voom_automatic.vim
