### ISSUE TITLE
voom + latex : use input file

### ISSUE THREAD

**Issue by maieul** [vim-voom/vim-voom.github.com#22]
A big challenge for voom should be to enable to have a Tree which is not limited to to the current file, but to all the file called by a input. It will allow to move from file to file, but to keep the tree from the main file.

For example I have a file 

chapter.tex which only contain \chapter command + introduction. It input one file by section.

**Comment by vim-voom** [comment]
I am not interested. Implementing such feature would result in massive
increase in complexity, both in the code and the user interface. I like
VOoM simple: one outline for one source buffer. It's better to have
dedicated Vim plugins for following links, managing files, etc.
For something complex and wonderful I recommend Leo:
http://leoeditor.com/
It functions as an outliner and project manager at the same time. Its
tree pane can contain different files and file sections.
