### ISSUE TITLE
Error when trying to call Voom

### ISSUE THREAD

**Issue by russurquhart1** [vim-voom/vim-voom.github.com#23]
On my windows mahcine, i have vim 7.3, and python is compiled in it. When i try and call :Voom asciidoc i get the following error messages:

Error detected while processing funciton voom#Init:
Line    40:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '__VOoM' is not defined

Can anyone shed some ligth on this?

Thanks,,
Russ

**Comment by vim-voom** [comment]
On 8/24/15, russurquhart1 <notifications@github.com> wrote:
> On my windows mahcine, i have vim 7.3, and python is compiled in it. When i
> try and call :Voom asciidoc i get the following error messages:
>
> Error detected while processing funciton voom#Init:
> Line    40:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> NameError: name '__VOoM' is not defined
>
>
> Can anyone shed some ligth on this?

You probably mean '_VOoM' (one underscore). My guess is that something
is wrong with VOoM installation. Try reinstalling it: first delete all
voom* files and directories in the $HOME/vimfiles, then copy the VOoM
package, than update helptags.

**Comment by vim-voom** [comment]
I hope you solved this.
