### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by naught101** [vim-voom/vim-voom.github.com#24]
I predominantly use python 3, and VoOM doesn't like it.

```
Error detected while processing /home/naught101/.dotfiles/.vim/bundle/VOoM/autoload/voom.vim:
line   48:
E319: Sorry, the command is not available in this version: python << EOF
line 2954:
E171: Missing :endif
E117: Unknown function: voom#Init
```

Is there any chance it will be made compatible with python 3? Or would you accept a pull-request? 

(Also, it would kind of make more sense to have this issue tracker on [the actual voom repository](https://github.com/vim-scripts/VOoM), rather than on the repository for the website, because then pull requests can be made that automatically resolve issues, etc.)

**Comment by vim-voom** [comment]
On 12/19/16, naught101 <notifications@github.com> wrote:
> I predominantly use python 3, and VoOM doesn't like it.
> ...
> Is there any chance it will be made compatible with python 3? Or would you
> accept a pull-request?

I am preparing new version 5.2 which will support both Python 2 and 3.
I expect to publish it by the end of January the latest.

> (Also, it would kind of make more sense to have this issue tracker on [the
> actual voom repository](https://github.com/vim-scripts/VOoM), rather than on
> the repository for the website, because then pull requests can be made that
> automatically resolve issues, etc.)

The actual voom repository is a mirror of current version at
http://www.vim.org/scripts/script.php?script_id=2657. I prefer to
upload to vim.org, but people kept pestering me about GitHub repo, so
I created it. You can post issues on either repo.

**Comment by naught101** [comment]
> You can post issues on either repo.

Issues seem to be disabled on the other repo. I can't see a way to post there. I CAN make pull requests, but I think most ideas for PRs should be discussed in issues first anyway..

> I am preparing new version 5.2 which will support both Python 2 and 3. I expect to publish it by the end of January the latest.

Awesome! Thank you. I look forward to it :)

**Comment by vim-voom** [comment]
On 12/21/16, naught101 <notifications@github.com> wrote:
>> You can post issues on either repo.
>
> Issues seem to be disabled on the other repo. I can't see a way to post
> there. I CAN make pull requests, but I think most ideas for PRs should be
> discussed in issues first anyway..

I meant this one: https://github.com/vim-voom/VOoM (There is already
request for Python 3 there).

https://github.com/vim-scripts/VOoM is updated by robots and I have no
control over it.

**Comment by naught101** [comment]
Ah, that makes sense. I see https://github.com/vim-voom/VOoM/issues/8

Perhaps the README should point to https://github.com/vim-voom/VOoM/issues instead of https://github.com/vim-voom/vim-voom.github.com/issues ?

**Comment by vim-voom** [comment]
Done in VOoM v5.2.
