### ISSUE TITLE
Ignore R comments within R chunks of an R markdown document

### ISSUE THREAD

**Issue by marvel64** [vim-voom/vim-voom.github.com#25]
Hi,

I am often editing `R markdown (*.Rmd, *.rmd)` documents, which are a mix of markdown and the R statistical language. The markdown flavor allows to incorporate R chunks like this (normally without the `i` at the end of the second ```, it was the only way to have the end of the chunk displayed somewhat correctly) :

# This is my markdown document

## My first calculation

```
```{r}
# this is an R comment, which will be interpreted as a markdown header in Voom
2 + 2
```i
```   

Voom will pick the comment within the `R` chunk up as a markdown element. Is there a way to avoid it?

Thank you!

**Comment by vim-voom** [comment]
You can use "pandoc" markup mode, but there must be no text after the
second ```.

**Comment by marvel64** [comment]
Works very well, thank you!!
