### ISSUE TITLE
Voomgrep leads to 'E21: Cannot make changes, 'modifiable is off'

### ISSUE THREAD

**Issue by OolonColoophid** [vim-voom/vim-voom.github.com#26]
Hi there

Great plugin, thanks.

When I run a :Voomgrep on a document (defined as pandoc) I get the quickfix list of matches as described in the help documentation. However, hitting return on any of the matches gets the above error. The document itself is writable, so perhaps Voom is trying to write to the Tree Buffer?

Any thoughts appreciated.

Cheers

Ian

**Comment by vim-voom** [comment]
This is strange. Does Quickfix work as expected without VOoM? That is,
open Pandoc file, create Quickfix list for it with eg

	:vimgrep /^#/j %
	:copen

and hit Return or double click to jump.

**Comment by OolonColoophid** [comment]
Thanks for getting to me. Doing the above, I get precisely the same error. (Having never used vimgrep, I didn't think to check this.)

**Comment by OolonColoophid** [comment]
I had another think about this today, and I realised that I'd remapped <CR> in normal mode to 'O', in order to add lines in a file without entering insert mode. Of course, this also applies to the QuickFix window.

Leaving this 'solution' here in case anyone else has the same problem.
